---

- name: Check COSI directory
  become: true
  file:
      path="{{ cosi_directory }}"
      owner="{{ cosi_owner }}"
      group="{{ cosi_group }}"
      mode="0755"
      state="directory"


- name: Check COSI bin directory
  become: true
  file:
      path="{{ cosi_directory }}/bin"
      owner="{{ cosi_owner }}"
      group="{{ cosi_group }}"
      mode="0755"
      state="directory"


- name: Check log directory
  become: true
  file:
      path="{{ log_directory }}"
      owner="{{ cosi_owner }}"
      group="{{ cosi_group }}"
      mode="0755"
      state="directory"

- name: Unpack COSI Site package
  become: true
  unarchive:
      src="cosi-site-{{ cosi_site_version }}.tar.gz"
      dest="{{ cosi_directory }}"
      copy="yes"
      owner="{{ cosi_owner }}"
      group="{{ cosi_group }}"
  notify: Restart Site

- name: Install COSI Site config
  become: true
  template:
      src="cosi-site.json.j2"
      dest="{{ cosi_directory }}/etc/cosi-site.json"
      owner="{{ cosi_owner }}"
      group="{{ cosi_group }}"
      mode="0640"
  notify: Restart Site

- name: Install 'bunyan' nodejs module
  become: true
  npm: executable="{{ npm_bin }}" path="{{ cosi_directory }}"  state="present" name="bunyan" version="1.8.1"
  notify: Restart Site

- name: Install 'commander' nodejs module
  become: true
  npm: executable="{{ npm_bin }}" path="{{ cosi_directory }}"  state="present" name="commander" version="2.9.0"
  notify: Restart Site

- name: Install 'node-statsd' nodejs module
  become: true
  npm: executable="{{ npm_bin }}" path="{{ cosi_directory }}"  state="present" name="node-statsd" version="0.1.1"
  notify: Restart Site

- name: Install 'restify' nodejs module
  become: true
  npm: executable="{{ npm_bin }}" path="{{ cosi_directory }}"  state="present" name="restify" version="4.1.1"
  notify: Restart Site
